### ISSUE TITLE
Fix code to work with upgraded pandas

### ISSUE THREAD

**Issue by virgesmith** [nismod/household_microsynth#12]
Running on ARC3 revealed that the code doesn't work with pandas 0.21.0 (AttributeError: 'Series' object has no attribute 'columns' in unlistify). For now have downgraded the condas env to pandas 0.17.1.

This will need to be resolved properly at some point
